# Generated by Django 5.0.6 on 2024-06-17 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_like_liked_remove_like_liked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringevent',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteeringevent',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
