# Generated by Django 5.0.6 on 2024-06-17 11:53

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_volunteeringevent_time_alter_volunteeringevent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringevent',
            name='time',
            field=models.DateTimeField(default=main_app.models.VolunteeringEvent.default_time),
        ),
    ]
