# Generated by Django 5.0.6 on 2024-06-17 11:55

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_volunteeringevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringevent',
            name='time',
            field=models.TimeField(default=main_app.models.VolunteeringEvent.default_time),
        ),
    ]
