# Generated by Django 5.0.6 on 2024-06-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_volunteeringevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringevent',
            name='volunteers_needed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
